### ISSUE TITLE
gtfs-etl: running analyze-gtfs-stat results in error

### ISSUE THREAD

**Issue by OriHoch** [hasadna/open-bus#345]
**reproduction steps**

* Follow the [README for local development](https://github.com/hasadna/open-bus-gtfs-etl#development-using-local-python-interpreter)
* Download gtfs data:
```
$ open-bus-gtfs-etl download-gtfs .data/gtfs_data
2021-08-15 15:51:40,074 - root - INFO - Downloading GTFS files into: .data/gtfs_data
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:40<00:00, 10.03s/it]

gtfs: ".data/gtfs_data/israel-public-transportation.zip"
tariff: ".data/gtfs_data/Tariff.zip"
cluster_to_line: ".data/gtfs_data/ClusterToLine.zip"
trip_id_to_date: ".data/gtfs_data/TripIdToDate.zip"
```
* Run the analyze-gtfs-stat command:
```
$ open-bus-gtfs-etl analyze-gtfs-stat --gtfs-metadata-file .data/gtfs_data/.gtfs_metadata.json --output-folder .data/analyzed/
```

**expected**
* exits successfully

**actual**
* error:
```
2021-08-15 16:06:25,723 - root - INFO - analyze gtfs stat - this could take some minutes
2021-08-15 16:10:50,942 - root - DEBUG - Finished compute_route_stats from trip stats result
2021-08-15 16:10:50,959 - root - ERROR - Saving dataframe as data/analyzed/trip_stats.csv.gz is not supported
Traceback (most recent call last):
  File "/home/ori/open-bus-gtfs-etl/venv/bin/open-bus-gtfs-etl", line 33, in <module>
    sys.exit(load_entry_point('open-bus-gtfs-etl', 'console_scripts', 'open-bus-gtfs-etl')())
  File "/home/ori/open-bus-gtfs-etl/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ori/open-bus-gtfs-etl/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ori/open-bus-gtfs-etl/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ori/open-bus-gtfs-etl/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ori/open-bus-gtfs-etl/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ori/open-bus-gtfs-etl/open_bus_gtfs_etl/cli.py", line 48, in analyze_gtfs_stat
    api.analyze_gtfs_stat(gtfs_metadata_file=gtfs_metadata_file.decode() if gtfs_metadata_file else None,
  File "/home/ori/open-bus-gtfs-etl/open_bus_gtfs_etl/api.py", line 53, in analyze_gtfs_stat
    dump_trip_and_route_stat(trip_stat=trip_stats, route_stat=route_stats, output_folder=output_folder)
  File "/home/ori/open-bus-gtfs-etl/open_bus_gtfs_etl/gtfs_stat/gtfs_stats.py", line 42, in dump_trip_and_route_stat
    save_dataframe_to_file(trip_stat, output_folder.joinpath(TRIP_STAT_FILE_NAME))
  File "/home/ori/open-bus-gtfs-etl/open_bus_gtfs_etl/gtfs_stat/output.py", line 25, in save_dataframe_to_file
    raise err
NotImplementedError: Saving dataframe as data/analyzed/trip_stats.csv.gz is not supported
```

**Comment by AvivSela** [comment]
solved by: https://github.com/hasadna/open-bus-gtfs-etl/pull/5
